USE [Moula]
GO

SET ANSI_PADDING ON
GO
DROP INDEX IF EXISTS idxReference ON PaymentRequests
GO
/****** Object:  Index [idxReference]    Script Date: 23/08/2020 8:31:12 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [idxReference] ON [dbo].[PaymentRequests]
(
	[Reference] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


